array = ["http://therealisticorganizer.blogspot.com/2014/12/engagement-survival-kit.html",
"http://therealisticorganizer.blogspot.com/2014/11/what-im-thankful-for.html",
"http://therealisticorganizer.blogspot.com/2015/01/year-in-review-2014.html",
"http://therealisticorganizer.blogspot.com/2014/11/organizing-for-holidays.html",
"http://therealisticorganizer.blogspot.com/2014/07/upgrade-old-frames-and-address-hoarding.html",
"http://therealisticorganizer.blogspot.com/2014/08/organized-weekly-dinners_22.html",
"http://therealisticorganizer.blogspot.com/2014/09/balcony-update-cinder-block-bench.html",
"http://therealisticorganizer.blogspot.com/2014/12/diy-holiday-decorations-and-gift-ideas.html",
"http://therealisticorganizer.blogspot.com/2014/08/organizing-digital-pictures-without.html",
"http://therealisticorganizer.blogspot.com/2014/09/updating-old-jewelry-box.html",
"http://therealisticorganizer.blogspot.com/2014/09/hello-from-moorea.html",
"http://therealisticorganizer.blogspot.com/2014/10/how-to-organize-cords-using-shoe.html",
"http://therealisticorganizer.blogspot.com/2014/10/organized-travel-abroad.html",
"http://therealisticorganizer.blogspot.com/2014/05/outdoor-party-bucket-with-table.html",
"http://therealisticorganizer.blogspot.com/2014/04/organizing-handyman-supplies.html",
"http://therealisticorganizer.blogspot.com/2014/03/5-diy-art-frames-under-10.html",
"http://therealisticorganizer.blogspot.com/2014/03/diy-mini-vase.html",
"http://therealisticorganizer.blogspot.com/2014/07/gardening-in-manhattan.html",
"http://therealisticorganizer.blogspot.com/2014/02/gettin-crafty-with-cork.html",
"http://therealisticorganizer.blogspot.com/2014/04/organizing-recipes-for-1.html",
"http://therealisticorganizer.blogspot.com/2014/03/off-wall-organizing-in-kitchen.html",
"http://therealisticorganizer.blogspot.com/2014/02/pursenal-problems-clearing-out.html",
"http://therealisticorganizer.blogspot.com/2014/01/dumping-dish-upgrade-with-diy.html",
"http://therealisticorganizer.blogspot.com/2014/01/organized-slow-cooker-freezer-meals.html",
"http://therealisticorganizer.blogspot.com/2013/12/diy-holiday-decorating.html",
"http://therealisticorganizer.blogspot.com/2014/01/cleaning-up-christmas.html",
"http://therealisticorganizer.blogspot.com/2013/12/organizing-for-others-cords-part-1.html",
"http://therealisticorganizer.blogspot.com/2013/11/love-letters-organizing-your-meaningful.html",
"http://therealisticorganizer.blogspot.com/2013/10/repurposed-cosmetic-organizer.html",
"http://therealisticorganizer.blogspot.com/2013/10/organizing-for-others-under-sink.html",
"http://therealisticorganizer.blogspot.com/2013/09/how-to-unclutter-you-kitchen-drawer.html",
"http://therealisticorganizer.blogspot.com/2013/08/spice-up-your-life-magnetic-spice-rack.html",
"http://therealisticorganizer.blogspot.com/2013/07/folding-for-travel-and-more.html",
"http://therealisticorganizer.blogspot.com/2013/07/planning-babys-1st-birthday.html",
"http://therealisticorganizer.blogspot.com/2013/07/carry-on-travel-for-over-packer.html",
"http://therealisticorganizer.blogspot.com/2013/05/the-chaotic-kitchen-cupboard.html",
"http://therealisticorganizer.blogspot.com/2013/05/welcome.html",
"http://therealisticorganizer.blogspot.com/2013/05/the-seasonal-switch.html"]
new_array = []
array.collect do |url|
  new_array << "http://localhost:5000/posts/#{url.split("/")[-1]}"
end
puts new_array
